### ISSUE TITLE
Rename 'Recent Kills' on player profiles to 'Recent Encounters'

### ISSUE THREAD

**Issue by residal** [Warzone/website#74]
In the recent kills section on a player's profile, it doesn't only list kills. It also lists deaths. 'Recent Encounters' would be a more suitable title for this section.

Reference:
![image](https://user-images.githubusercontent.com/55336990/68025079-0a87a580-fd00-11e9-8a57-94988fa09c31.png)

**Comment by BennyDoesTheStuff** [comment]
Wouldn’t it be better to instead just split up the recent deaths and kills to be separated and then only showing the recent 5 or 6 for each column?

**Comment by jellz** [comment]
I personally prefer the current solution where 'Recent Kills' shows any deaths involving the player, no matter if they are the attacker or victim.
