### ISSUE TITLE
Player stat page doesn't show skin overlay

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/website#78]
![Example](https://user-images.githubusercontent.com/47429979/68772164-f2146680-05ee-11ea-8c14-d166033f006e.PNG)
The skin doesn't fit within the main information box as seen above.

Note: The image also doesn't display the secondary layer of the skin.

**Comment by jellz** [comment]
> The skin doesn't fit within the main information box as seen above.
This is intended

> Note: The image also doesn't display the secondary layer of the skin.
Yep, that's a bug

**Comment by jellz** [comment]
Actually, just checked, the page does show the overlay now
