### ISSUE TITLE
The wilderness needs a stats page to show how buff it is

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/website#79]
![Example](https://user-images.githubusercontent.com/47429979/68773703-a6af8780-05f1-11ea-846b-5850b2f87590.PNG)
There is no link to go to Wilderness' page, nor does a skin load because there's no uuid attached.

Solutions would be to use a steve/alex skin (or if you're feeling ambitious, grab the nick skin), then just make a temporary player stats page until the nick is changed.

**Comment by Draem** [comment]
Wilderness is the void or fall damage

**Comment by BennyDoesTheStuff** [comment]
I mean I think it’s fine

**Comment by BennyDoesTheStuff** [comment]
We could always just make it unclickable if it’s wilderness
